/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrackRecordRouteImport } from './routes/track-record'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RiskDisclaimerRouteImport } from './routes/risk-disclaimer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PammRouteImport } from './routes/pamm'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EaLicensingRouteImport } from './routes/ea-licensing'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectBrokerRouteImport } from './routes/connect-broker'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivateLicenseRouteImport } from './routes/activate-license'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRecordRoute = TrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclaimerRoute = RiskDisclaimerRouteImport.update({
  id: '/risk-disclaimer',
  path: '/risk-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PammRoute = PammRouteImport.update({
  id: '/pamm',
  path: '/pamm',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EaLicensingRoute = EaLicensingRouteImport.update({
  id: '/ea-licensing',
  path: '/ea-licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectBrokerRoute = ConnectBrokerRouteImport.update({
  id: '/connect-broker',
  path: '/connect-broker',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateLicenseRoute = ActivateLicenseRouteImport.update({
  id: '/activate-license',
  path: '/activate-license',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate-license': typeof ActivateLicenseRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/connect-broker': typeof ConnectBrokerRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/ea-licensing': typeof EaLicensingRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pamm': typeof PammRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/risk-disclaimer': typeof RiskDisclaimerRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate-license': typeof ActivateLicenseRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/connect-broker': typeof ConnectBrokerRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/ea-licensing': typeof EaLicensingRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pamm': typeof PammRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/risk-disclaimer': typeof RiskDisclaimerRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate-license': typeof ActivateLicenseRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/connect-broker': typeof ConnectBrokerRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/ea-licensing': typeof EaLicensingRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pamm': typeof PammRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/risk-disclaimer': typeof RiskDisclaimerRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/track-record': typeof TrackRecordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate-license'
    | '/admin'
    | '/affiliate'
    | '/auth-callback'
    | '/checkout'
    | '/checkout-success'
    | '/connect-broker'
    | '/contact'
    | '/dashboard'
    | '/documentation'
    | '/ea-licensing'
    | '/faq'
    | '/forgot-password'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/pamm'
    | '/pricing'
    | '/privacy'
    | '/risk-disclaimer'
    | '/signup'
    | '/terms'
    | '/track-record'
    | '/verify-email'
    | '/insights/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate-license'
    | '/admin'
    | '/affiliate'
    | '/auth-callback'
    | '/checkout'
    | '/checkout-success'
    | '/connect-broker'
    | '/contact'
    | '/dashboard'
    | '/documentation'
    | '/ea-licensing'
    | '/faq'
    | '/forgot-password'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/pamm'
    | '/pricing'
    | '/privacy'
    | '/risk-disclaimer'
    | '/signup'
    | '/terms'
    | '/track-record'
    | '/verify-email'
    | '/insights/$slug'
  id:
    | '__root__'
    | '/'
    | '/activate-license'
    | '/admin'
    | '/affiliate'
    | '/auth-callback'
    | '/checkout'
    | '/checkout-success'
    | '/connect-broker'
    | '/contact'
    | '/dashboard'
    | '/documentation'
    | '/ea-licensing'
    | '/faq'
    | '/forgot-password'
    | '/insights'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/pamm'
    | '/pricing'
    | '/privacy'
    | '/risk-disclaimer'
    | '/signup'
    | '/terms'
    | '/track-record'
    | '/verify-email'
    | '/insights/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateLicenseRoute: typeof ActivateLicenseRoute
  AdminRoute: typeof AdminRoute
  AffiliateRoute: typeof AffiliateRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ConnectBrokerRoute: typeof ConnectBrokerRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DocumentationRoute: typeof DocumentationRoute
  EaLicensingRoute: typeof EaLicensingRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PammRoute: typeof PammRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RiskDisclaimerRoute: typeof RiskDisclaimerRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrackRecordRoute: typeof TrackRecordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-record': {
      id: '/track-record'
      path: '/track-record'
      fullPath: '/track-record'
      preLoaderRoute: typeof TrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclaimer': {
      id: '/risk-disclaimer'
      path: '/risk-disclaimer'
      fullPath: '/risk-disclaimer'
      preLoaderRoute: typeof RiskDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pamm': {
      id: '/pamm'
      path: '/pamm'
      fullPath: '/pamm'
      preLoaderRoute: typeof PammRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ea-licensing': {
      id: '/ea-licensing'
      path: '/ea-licensing'
      fullPath: '/ea-licensing'
      preLoaderRoute: typeof EaLicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-broker': {
      id: '/connect-broker'
      path: '/connect-broker'
      fullPath: '/connect-broker'
      preLoaderRoute: typeof ConnectBrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-license': {
      id: '/activate-license'
      path: '/activate-license'
      fullPath: '/activate-license'
      preLoaderRoute: typeof ActivateLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateLicenseRoute: ActivateLicenseRoute,
  AdminRoute: AdminRoute,
  AffiliateRoute: AffiliateRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ConnectBrokerRoute: ConnectBrokerRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DocumentationRoute: DocumentationRoute,
  EaLicensingRoute: EaLicensingRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InsightsRoute: InsightsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PammRoute: PammRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RiskDisclaimerRoute: RiskDisclaimerRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrackRecordRoute: TrackRecordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
